update filtering

diff --git a/src/zlibs/filters b/src/zlibs/filters
--- a/src/zlibs/filters
+++ b/src/zlibs/filters
@@ -207,161 +207,154 @@ EOF
 
 
 filter_maildir() {
-    fn filter_maildir
-    req=(MAILDIRS)
-    ckreq || return 1
+  fn filter_maildir
+  req=(MAILDIRS)
+  ckreq || return 1
 
-    # Makes glob matching case insensitive
-    unsetopt CASE_MATCH
+  # Makes glob matching case insensitive
+  unsetopt CASE_MATCH
 
-    # default maildir to filter is incoming
-    mdinput="${1:-${MAILDIRS}/incoming}"
+  # default maildir to filter is incoming
+  mdinput="${1:-${MAILDIRS}/incoming}"
 	srcpath=`realpath "$mdinput"`
 
-    maildircheck "$srcpath" || {
-        error "Invalid maildir: $mdinput"
-        return 1
-    }
+  maildircheck "$srcpath" || {
+    error "Invalid maildir: $mdinput"
+    return 1
+  }
 
-    # for safety we bail out in case the final fallback
-    # maildir is not existing. unsorted should always
-    # be there.
-    maildirmake "$MAILDIRS/unsorted"
+  # for safety we bail out in case the final fallback
+  # maildir is not existing. unsorted should always
+  # be there.
+  maildirmake "$MAILDIRS/unsorted"
 
-    # loads up the filter cache (zsh compiled arrays)
-    [[ -r "$MAILDIRS/cache/filters" ]] &&
-        source $MAILDIRS/cache/filters
+  # loads up the filter cache (zsh compiled arrays)
+  [[ -r "$MAILDIRS/cache/filters" ]] &&
+    source $MAILDIRS/cache/filters
 
 	if command -v mlist > /dev/null; then
 		mails=`mlist "$srcpath"`
 	else
  		mails=`${=find} "$srcpath" -maxdepth 2 -type f`
 	fi
-    numm=`print $mails | wc -l`
+  numm=`print $mails | wc -l`
 
-    [[ $numm = 0 ]] && {
-        error "Nothing to filter inside maildir $mdinput"
-        return 1
+  [[ $numm = 0 ]] && {
+    error "Nothing to filter inside maildir $mdinput"
+    return 1
+  }
+
+  notice "Filtering maildir: $mdinput ($numm mails)"
+  c=0
+
+  for m in ${(f)mails}; do
+
+    # clean interrupt
+    [[ $global_quit = 1 ]] && {
+      error "User break requested, interrupting operation"
+			return 1
     }
 
-    notice "Filtering maildir: $mdinput ($numm mails)"
-    c=0
+    match=0
+    c=$(($c + 1))
 
-    for m in ${(f)mails}; do
-
-        # clean interrupt
-        [[ $global_quit = 1 ]] && {
-            error "User break requested, interrupting operation"
-            break
-        }
-
-        match=0
-        c=$(($c + 1))
-
-        # check if its an empty file
-        _fsize=`zstat +size "$m"`
-        [[ $_fsize = 0 ]] && {
-            act "$c\t/ $numm\t(empty)"
-            rm "$m"
-            continue
-        }
+    # check if its an empty file
+    _fsize=`zstat +size "$m"`
+    [[ $_fsize = 0 ]] && {
+      act "$c\t/ $numm\t(empty)"
+      rm "$m"
+      continue
+    }
 
 		# print progress for each 1000 mails processed if many
 		(( $c > 999 )) && (( $c % 1000 == 0 )) &&
 			act "$c\t/ $numm processed"
 
-        # hdr "$m" | awk '/Sender.*mailman-bounce/ { exit 1 }'
-        # [[ $? = 0 ]] || {
-        #     [[ "$mdinput" = "zz.bounces" ]] && {
-        #         act "$c\t/ $numm"
-        #         continue
-        #     }
-        #     act "$c\t/ $numm\t-> zz.bounces"
-        #     [[ $DRYRUN = 1 ]] || {
-        #         printfile "$m" | deliver zz.bounces
-        #         [[ $? = 0 ]] && { rm "$m" }
-        #         continue
-        #     }
-        # }
-
-        func "processing through own filters"
-
-        # run all filter regexps on the from: field
-        local _dest=""
+    # run all filter regexps on the from: field
+    local _dest=""
 		# this also sets the mblaze sequence to avoid warnings
 		mseq -c "$m"
 		local femail=`maddr -h from -a`
 
 		# fuzzy match if in own Filters.txt
-        for exp in ${(k)filter_from}; do
+    for exp in ${(k)filter_from}; do
 			[[ $global_quit = 1 ]] && {
 				error "User break requested, interrupting operation"
-				break }
+				return 1 }
 			local found=0
 			if [[ "$femail" == "$exp" ]]; then
 				found=1
 			elif [[ "$femail" =~ "$exp" ]]; then
 				found=1	# fuzzy match on a string (PCRE)
 			fi
-            [[ "$found" == "1" ]] && {
-                # retrieve the filter destination maildir
-                _dest="${filter_from[$exp]}"
-				target=`realpath "${MAILDIRS}/$_dest"`
-                # if destination maildir is same as input, skip
-                func "check: $target == $srcpath"
-                [[ "$target" == "$srcpath" ]] && {
-                    func "$c\t/ $numm"
-                    match=1
-                    break
-                }
-                act "$c\t/ $numm\t-> $_dest\t(from $femail)"
-                # tag mailinglists
-                [[ $DRYRUN = 1 ]] || {
-					mrefile "$m" "$target"
-					if [[ $? = 0 ]]; then
-						match=1
-						break
-					else
-						error "Filter error: $m -> $target"
-					fi
-				}
-            }
-        done
+			(( $found == 1 )) || continue
+			func "Filter from: $femail"
+      # retrieve the filter destination maildir
+      _dest="${filter_from[$exp]}"
+			target=`realpath "${MAILDIRS}/$_dest"`
+      # if destination maildir is same as input, skip
+      func "check: $target == $srcpath"
+      [[ "$target" == "$srcpath" ]] && {
+        func "$c\t/ $numm"
+        match=1
+        break
+      }
+      act "$c\t/ $numm\t-> $_dest\t(from $femail)"
+      # tag mailinglists
+      [[ $DRYRUN = 1 ]] || {
+				mrefile "$m" "$target"
+				if [[ $? = 0 ]]; then
+					match=1
+					break
+				else
+					error "Filter error: $m -> $target"
+				fi
+			}
+    done
 
-        [[ "$match" = "1" ]] && {
-            func "matched filter from: field"
-            continue
-        }
+    [[ "$match" = "1" ]] && {
+      func "matched filter from: field"
+      continue
+    }
 
-        _dest=""
-        # run all filter regexps on the to: and cc: fields
+    _dest=""
+    # run all filter regexps on the to: and cc: fields
 		tocc_addr=(`print "$m" | maddr -a -h to:cc | sort | uniq`)
-        for ft in ${(f)tocc_addr}; do
+    for ft in ${(f)tocc_addr}; do
 			[[ $global_quit = 1 ]] && {
 				error "User break requested, interrupting operation"
 				break }
-            for exp in ${(k)filter_to}; do
+      for exp in ${(k)filter_to}; do
 				[[ $global_quit = 1 ]] && {
 					error "User break requested, interrupting operation"
 					break }
 				local found=0
-				if [[ "$ft" == "$exp" ]]; then found=1
-											   # fuzzy match on a string (PCRE)
-				elif [[ "$ft" =~ "$exp" ]]; then found=1
+				if [[ "$ft" == "$exp" ]]; then
+          found=1
+				elif [[ "$ft" =~ "$exp" ]]; then
+          found=1 # fuzzy match on a string (PCRE)
 				fi
 				(( $found == 1 )) || continue
-                # retrieve the filter destination maildir
-                _dest="${filter_to[$exp]}"
+			  func "Filter to: $ft"
+        # retrieve the filter destination maildir
+        _dest="${filter_to[$exp]}"
+        [[ "$_dest" == "" ]] && {
+          error "Broken filter, destination not found: $exp"
+          continue
+        }
+        func "Dest: $_dest"
 				target=`realpath "${MAILDIRS}/$_dest"`
-                # if destination maildir is same as input, skip
-                [[ "$target" == "$srcpath" ]] && {
-                    func "$c\t/ $numm"
+        func "Target: $target"
+        # if destination maildir is same as input, skip
+        [[ "$target" == "$srcpath" ]] && {
+          func "$c\t/ $numm"
 					match=1
-                    break
-                }
-                act "$c\t/ $numm\t-> $_dest\t(to $ft)"
-                # tag mailinglists
-                [[ $DRYRUN = 1 ]] || {
+          break
+        }
+        act "$c\t/ $numm\t-> $_dest\t(to $ft)"
+        # tag mailinglists
+        [[ $DRYRUN = 1 ]] || {
+          [[ -d "${target}" ]] || maildirmake "${target}"
 					mrefile "$m" "$target"
 					if [[ $? = 0 ]]; then
 						match=1
@@ -370,14 +363,14 @@ filter_maildir() {
 						error "Refile error: $m -> $target"
 					fi
 				}
-            done
-            [[ "$match" = "1" ]] && { break }
-        done
+      done
+      [[ "$match" = "1" ]] && { break }
+    done
 
-        [[ "$match" = "1" ]] && {
-            func "matched filter to:/cc: fields"
-            continue
-        }
+    [[ "$match" = "1" ]] && {
+      func "matched filter to:/cc: fields"
+      continue
+    }
 
 		[[ $global_quit = 1 ]] && {
 			error "User break requested, interrupting operation"
@@ -386,12 +379,12 @@ filter_maildir() {
 		# simple match if in whitelist
 		(( ${filter_whitelist[(Ie)$femail]} )) && {
 			target=`realpath "${MAILDIRS}/known"`
-            [[ "$target" == "$srcpath" ]] && {
-                func "$c\t/ $numm"
+      [[ "$target" == "$srcpath" ]] && {
+        func "$c\t/ $numm"
 				continue
-            }
-            act "$c\t/ $numm\t-> known\t(from $femail)"
-            [[ $DRYRUN = 1 ]] || {
+      }
+      act "$c\t/ $numm\t-> known\t(from $femail)"
+      [[ $DRYRUN = 1 ]] || {
 				mrefile "$m" "$target"
 				if [[ $? = 0 ]]; then
 					func "matched whitelist from: field"
@@ -399,7 +392,7 @@ filter_maildir() {
 				else
 					error "Refile error: $m -> $target"
 				fi
-            }
+      }
 		}
 
 		[[ $global_quit = 1 ]] && {
@@ -407,15 +400,15 @@ filter_maildir() {
 			break }
 
 		# X-Spam flag set server-side
-        print "$m" | mpick -t '"X-Spam-Flag" =~ "YES"'
-        [[ $? = 0 ]] || {
+    print "$m" | mpick -t '"X-Spam-Flag" =~ "YES"'
+    [[ $? = 0 ]] || {
 			target=`realpath "${MAILDIRS}/zz.spam"`
-            [[ "$target" = "$srcpath" ]] && {
-                func "$c\t/ $numm"
-                continue
-            }
-            act "$c\t/ $numm\t-> zz.spam"
-            [[ $DRYRUN = 1 ]] || {
+      [[ "$target" = "$srcpath" ]] && {
+        func "$c\t/ $numm"
+        continue
+      }
+      act "$c\t/ $numm\t-> zz.spam"
+      [[ $DRYRUN = 1 ]] || {
 				maildirmake "$target"
 				mrefile "$m" "$target"
 				if [[ $? = 0 ]]; then
@@ -424,8 +417,8 @@ filter_maildir() {
 				else
 					error "Refile error: $m -> $target"
 				fi
-            }
-        }
+      }
+    }
 
 		[[ $global_quit = 1 ]] && {
 			error "User break requested, interrupting operation"
@@ -434,12 +427,12 @@ filter_maildir() {
 		# simple match if in blacklist
 		(( ${filter_blacklist[(Ie)$femail]} )) && {
 			target=`realpath "${MAILDIRS}/zz.blacklist"`
-            [[ "$target" == "$srcpath" ]] && {
-                func "$c\t/ $numm"
+      [[ "$target" == "$srcpath" ]] && {
+        func "$c\t/ $numm"
 				continue
-            }
-            act "$c\t/ $numm\t-> zz.blacklist\t(from $femail)"
-            [[ $DRYRUN = 1 ]] || {
+      }
+      act "$c\t/ $numm\t-> zz.blacklist\t(from $femail)"
+      [[ $DRYRUN = 1 ]] || {
 				maildirmake "$target"
 				mrefile "$m" "$target"
 				if [[ $? = 0 ]]; then
@@ -448,26 +441,26 @@ filter_maildir() {
 				else
 					error "Refile error: $m -> $target"
 				fi
-            }
+      }
 		}
 
-        # parse own email and aliases
-        match=0
+    # parse own email and aliases
+    match=0
 		target=`realpath "${MAILDIRS}/priv"`
-        for f in ${(f)tocc_addr}; do
+    for f in ${(f)tocc_addr}; do
 			[[ $global_quit = 1 ]] && {
 				error "User break requested, interrupting operation"
 				break }
 
-            # check if destination address is in filter_own array
-            [[ ${filter_own[(r)$f]} == ${f} ]] && {
-                [[ "$target" = "$srcpath" ]] && {
-                    func "$c\t/ $numm"
-                    match=1
-                    break
-                }
-                act "$c\t/ $numm\t-> priv"
-                [[ $DRYRUN = 1 ]] || {
+      # check if destination address is in filter_own array
+      [[ ${filter_own[(r)$f]} == ${f} ]] && {
+        [[ "$target" = "$srcpath" ]] && {
+          func "$c\t/ $numm"
+          match=1
+          break
+        }
+        act "$c\t/ $numm\t-> priv"
+        [[ $DRYRUN = 1 ]] || {
 					mrefile "$m" "$target"
 					if [[ $? = 0 ]]; then
 						func "matched own address in to/cc: fields"
@@ -476,34 +469,34 @@ filter_maildir() {
 					else
 						error "Refile error: $m -> $target"
 					fi
-                }
-            }
-        done
+        }
+      }
+    done
 
-        [[ $match == 1 ]] && continue
+    [[ $match == 1 ]] && continue
 		[[ $global_quit = 1 ]] && {
 			error "User break requested, interrupting operation"
 			break }
 
-        # if here then file to unsorted
+    # if here then file to unsorted
 		target=`realpath "${MAILDIRS}/unsorted"`
-        if [ "$target" = "$srcpath" ]; then
-            func "$c\t/ $numm"
-        else
-            act "$c\t/ $numm\t-> unsorted"
-            [[ $DRYRUN = 1 ]] || {
+    if [ "$target" = "$srcpath" ]; then
+      func "$c\t/ $numm"
+    else
+      act "$c\t/ $numm\t-> unsorted"
+      [[ $DRYRUN = 1 ]] || {
 				mrefile "$m" "$target"
 				if [[ $? = 0 ]]; then
 					func "no match found, sent to unsorted"
 				else
 					error "Refile error: $m -> $target"l
 				fi
-            }
-        fi
+      }
+    fi
 
-    done
+  done
 
-    return 0
+  return 0
 }
 
 
