started port to Cygwin (using babun)

diff --git a/src/zlibs/keyring b/src/zlibs/keyring
--- a/src/zlibs/keyring
+++ b/src/zlibs/keyring
@@ -90,15 +90,15 @@ ask_password() {
 		fi
 		return 0
 	    elif [ -r "$KEYRING" ]; then
-                func "Looking for password in local keyring for $email ($account)"
+                func "looking for password in local keyring for $email ($account)"
 		func "new pass hash for: $login:$host"
 		_hash=`print "$login:$host" | shasum | awk '{print $1}'`
 		lookup="`lookup_secret ${_hash}`"
 		{ test "$lookup" = "" } || {
-		    act "Saved password found for $email ($transport on $host)"
-		    notice "Type the password to unlock this keyring entry:"
-		    password="`print - $lookup | base64 -d | gpg -d --cipher-algo AES256 --openpgp --no-options`"
-		    { test "$?" = 0 } || { error "Incorrect password to unlock local keyring entry, operation aborted."; return 1 }
+		    act "saved password found for $email ($transport on $host)"
+		    notice "type the password to unlock this keyring entry:"
+		    password="`print - $lookup | base64 -d | gpg -d --cipher-algo aes256 --openpgp --no-options`"
+		    { test "$?" = 0 } || { error "incorrect password to unlock local keyring entry, operation aborted."; return 1 }
 		    return 0
 		}
 	    fi
@@ -111,8 +111,26 @@ ask_password() {
 	    return 0
 	    ;;
 	*)
-	    error "Unknown system, can't figure out how to handle passwords"
-	    return 1
+                func "looking for password in local keyring for $email ($account)"
+		func "new pass hash for: $login:$host"
+		_hash=`print "$login:$host" | shasum | awk '{print $1}'`
+		lookup="`lookup_secret ${_hash}`"
+		{ test "$lookup" = "" } || {
+		    act "saved password found for $email ($transport on $host)"
+		    notice "type the password to unlock this keyring entry:"
+		    password="`print - $lookup | base64 -d | gpg -d --cipher-algo aes256 --openpgp --no-options`"
+		    { test "$?" = 0 } || { error "incorrect password to unlock local keyring entry, operation aborted."; return 1 }
+		    return 0
+		}
+	    ####################
+	    # USE PINENTRY ALONE
+	    new_password
+	    { test $? != 0 } && {
+		error "Password input aborted."
+		return 1 }
+	    return 0
+	    ;;
+
     esac
 }
 
@@ -226,7 +244,36 @@ EOF
             
 	        ;;
 	    *)
-	        error "Unknown system, can't figure out how to handle passwords"
-	        return 1
+
+ 
+		        { test -r "$KEYRING" } || { create_keyring "$KEYRING" }
+
+                for h in "$imap" "$smtp"; do                
+		            # calculate the hash for this entry
+		            _hash=`print "$login:$host" | shasum | awk '{print $1}'`
+		            # check if the entry is already present
+		            func "new pass hash for: $login:$host"
+		            lookup="`lookup_secret ${_hash} rowid`"
+		            notice "Select the password to lock this keyring entry:"
+		            _password="`print - $password | gpg -c --cipher-algo AES256 --openpgp --no-options | base64`"
+                                        
+		            if [ "$lookup" = "" ]; then # new entry
+			            cat <<EOF | ${SQL} -batch "$KEYRING"
+INSERT INTO secrets (hash, password)
+VALUES ("${_hash}", "${_password}");
+EOF
+			            act "saved new password in local keyring"
+		            else # update entry
+			            cat <<EOF | ${SQL} -batch "$KEYRING"
+UPDATE secrets SET password="${_password}" WHERE hash LIKE "${_hash}";
+EOF
+			            act "updated local keyring with new password"
+		            fi
+                done
+
+
+
+		   
+		    ;;
     esac
 }
