relevant fixes to search, locking and mutt, plus speed improvements using zsh builtins

diff --git a/src/zlibs/locking b/src/zlibs/locking
--- a/src/zlibs/locking
+++ b/src/zlibs/locking
@@ -53,53 +53,55 @@ newlock() { # lock file, create if not existing
 
 pidcheck() { # check if lock belongs to us
     if [ -r "${1}.pid" ]; then
-
-	lockpid="`cat ${1}.pid`"
-	func "pidcheck: $lockpid"
-	if [ "$$" = "$lockpid" ]; then
-	    func "${1} lock belongs to us"
-	else
-
-	    error "Unlock attempt by multiple processes on `basename $1`"
-	    { test "$FORCE" = "1" } || { _prun=1
-		while [ "$_prun" = "1" ]; do
-		    for p in `ps ax | awk '{ print $1 }'`; do
-			{ test "$p" = "$lockpid" } && { break }
-		    done
-		    if [ "$p" = "$lockpid" ]; then
-			act "Owner (${lockpid}) still running, waiting release..."
-			sleep 1; continue
-		    else
-			act "Owner (${lockpid}) not running, taking over the lock"
-			rm -f "${1}.pid"; print "$$" > "${1}.pid"
-			_prun=0
-		    fi
-		done
-	    }
-	    act "left behind by $lockpid - we ($$) will take over"
-
-	fi
-
+        
+	    lockpid="`cat ${1}.pid`"
+	    func "pidcheck: $lockpid"
+	    if [[ "$$" = "$lockpid" ]]; then
+	        func "${1} lock belongs to us"
+	    else
+            
+	        error "Unlock attempt by multiple processes on `basename $1`"
+	        [[ "$FORCE" = "1" ]] || { _prun=1
+		        while [ "$_prun" = "1" ]; do
+                    [[ $global_quit = 1 ]] && { break }
+		            for p in `ps ax | awk '{ print $1 }'`; do
+			            { test "$p" = "$lockpid" } && { break }
+		            done
+		            if [ "$p" = "$lockpid" ]; then
+			            act "Owner (${lockpid}) still running, waiting release..."
+			            sleep 1; 
+                        continue
+		            else
+			            act "Owner (${lockpid}) not running, taking over the lock"
+			            rm -f "${1}.pid"; print "$$" > "${1}.pid"
+			            _prun=0
+		            fi
+		        done
+	        }
+	        act "left behind by $lockpid - we ($$) will take over"
+            
+	    fi
+        
     else # pid file doesn't exists
-	func "no pid file found for: $1"
-	func "we will take it over"
-	print "$$" > "${1}.pid"
+	    func "no pid file found for: $1"
+	    func "we will take it over"
+	    print "$$" > "${1}.pid"
     fi
     return 0
 }
 
 unlock() {
     func "unlock: $1"
-
+    
     pidcheck "$1"
-    { test $? = 0 } || { return 1 }
-
+    [[ $? = 0 ]] || { return 1 }
+    
     ${WORKDIR}/bin/dotlock -u "$1"
-    { test $? = 0 } || {
-	rm -f "$1.lock"
-	{ test $? = 0 } || { error "Unable to unlock: $1"; return 1 }
+    [[ $? = 0 ]] || {
+	    rm -f "$1.lock"
+	    [[ $? = 0 ]] || { error "Unable to unlock: $1"; return 1 }
     }
-    { test -r "${1}.pid" } && { rm -f "${1}.pid" }
+    [[ -r "${1}.pid" ]] && { rm -f "${1}.pid" }
     return 0
 }
 unlink() { # delete a file that we are locking
