minor fixes to locking and send

diff --git a/src/zlibs/locking b/src/zlibs/locking
--- a/src/zlibs/locking
+++ b/src/zlibs/locking
@@ -32,28 +32,32 @@ command -v dotlock > /dev/null
 
 lock() {
     func "$dotlock: $1"
-    ${=dotlock} ${1}
-    case $? in
+    ${=dotlock} "$1"
+    res=$?
+    case $res in
 	1) error "Cannot lock non existing file: $1"
 	    return 1 ;;
 	3) error "Locked file in use: $1"
 
-	    pidcheck ${1}
+	    pidcheck "$1"
 	    return 3 ;;
 
-	5) error "Impossible to lock: $1"
+	5) error "Lock is impossible on: $1"
 	    return 5 ;;
 	# success
-	0) echo "$$" > ${1}.pid
+	0) print "$$" > "$1.pid"
 	    return 0 ;;
+
+	*) error "Unknown error locking: $res"
+	    return 1 ;;
     esac
 }
 
 newlock() { # lock file, create if not existing
     func "creating locked file: $1"
-    touch $1
-    chmod 600 $1
-    lock $1
+    touch "$1"
+    chmod 600 "$1"
+    lock "$1"
 }
 
 pidcheck() { # check if lock belongs to us
@@ -76,7 +80,7 @@ pidcheck() { # check if lock belongs to us
 			sleep 1; continue
 		    else
 			act "Owner (${lockpid}) not running, taking over the lock"
-			rm -f ${1}.pid; print "$$" > ${1}.pid
+			rm -f "${1}.pid"; print "$$" > "${1}.pid"
 			_prun=0
 		    fi
 		done
@@ -88,7 +92,7 @@ pidcheck() { # check if lock belongs to us
     else # pid file doesn't exists
 	func "no pid file found for: $1"
 	func "we will take it over"
-	print "$$" > ${1}.pid
+	print "$$" > "${1}.pid"
     fi
     return 0
 }
