new tmpfile system and endgame() plus cleanups to addressbook import code

diff --git a/src/jaro b/src/jaro
--- a/src/jaro
+++ b/src/jaro
@@ -34,7 +34,6 @@ DEBUG=0
 DRYRUN=0
 CLEANEXIT=1
 CALLMUTT=1
-TMPRAM=0
 
 # global variables for binaries called
 typeset -h rm mkdir mutt
@@ -87,6 +86,71 @@ typeset -alU imap_info
 typeset -h muttflags
 
 autoload colors; colors
+
+# temporary directory
+typeset TMPPREFIX=${TMPPREFIX:-/tmp}
+typeset -H JAROTMP # Filename of secure temp just created (see _tmp_create())
+typeset -aH JAROTMPFILES      # Keep track of temporary files
+
+# Provide a random filename in shared memory
+_tmp_create() {
+    [[ -d "$TMPPREFIX" ]] || {
+        # we create the tempdir with the sticky bit on
+        sudo mkdir -m 1777 "$TMPPREFIX"
+        [[ $? == 0 ]] || _failure "Fatal error creating the temporary directory: ::1 temp dir::" "$TMPPREFIX"
+    }
+    
+    # We're going to add one more $RANDOM for each time someone complain
+    # about this being too weak of a random.
+    tfile="${TMPPREFIX}/$RANDOM$RANDOM$RANDOM$RANDOM"   # Temporary file
+    umask 066
+    [[ $? == 0 ]] || {
+        error "Fatal error setting the permission umask for temporary files"
+        return 1
+    }
+    
+    [[ -r "$tfile" ]] && {
+        error "Someone is messing up with us trying to hijack temporary files."
+        return 1
+    }
+    
+    touch "$tfile"
+    [[ $? == 0 ]] || {
+        error "Fatal error creating a temporary file: ::1 temp file::" "$tfile"
+        return 1
+    }
+    
+    [[ $? == 0 ]] || {
+        error "Fatal error setting ownership on temporary file: ::1 temp file::" "$tfile"
+        return 1
+    }
+    
+    func "Created tempfile: $tfile"
+    JAROTMP="$tfile"
+    JAROTMPFILES+=("$tfile")
+    
+    return 0
+}
+
+# Cleanup anything sensitive before exiting.
+_endgame() {
+    # Clear temporary files
+    for f in $JAROTMPFILES; do
+        func "endgame() cleaning tempfile $f"
+        rm -f "$f"
+    done
+    unset JAROTMPFILES
+}
+# Trap functions for the _endgame event
+TRAPINT()  { _endgame INT   }
+TRAPEXIT() { _endgame EXIT  }
+TRAPHUP()  { _endgame HUP   }
+TRAPQUIT() { _endgame QUIT  }
+TRAPABRT() { _endgame ABORT }
+TRAPKILL() { _endgame KILL  }
+TRAPPIPE() { _endgame PIPE  }
+TRAPTERM() { _endgame TERM  }
+TRAPSTOP() { _endgame STOP  }
 
 # standard output message routines
 # it's always useful to wrap them, in case we change behaviour later
@@ -197,47 +261,23 @@ fi
 ACCOUNTS="$MAILDIRS/Accounts"
 KEYRING="$MAILDIRS/Keyring"
 
-# temporary directory
-TMPDIR="$MAILDIRS/tmp/jaromil.$USER"
+
 case $OS in
-    GNU)
-    touch /dev/shm/test.jaromail.$USER > /dev/null
-    { test $? = 0 } && {
-    # we can use volatile ram
-        rm /dev/shm/test.jaromail.$USER
-        TMPDIR=/dev/shm/tmp.jaromail.$USER
-        TMPRAM=1
-    }
-
-    # backward compatibility tests for old paths in JaroMail <1.3
-    { test -d $WORKDIR/Accounts } && { test ! -d $ACCOUNTS } && {
-        act "Updating accounts location: $ACCOUNTS"
-        cp -ra $WORKDIR/Accounts $ACCOUNTS }
-
-    { test -r "$WORKDIR/keyring" } && { test ! -r "$KEYRING" } && {
-        act "Updating keyring location: $KEYRING"
-        cp $WORKDIR/keyring "$KEYRING" }
-
+    GNU)        
+        # backward compatibility tests for old paths in JaroMail <1.3
+        { test -d $WORKDIR/Accounts } && { test ! -d $ACCOUNTS } && {
+            act "Updating accounts location: $ACCOUNTS"
+            cp -ra $WORKDIR/Accounts $ACCOUNTS
+        }
+        
+        { test -r "$WORKDIR/keyring" } && { test ! -r "$KEYRING" } && {
+            act "Updating keyring location: $KEYRING"
+            cp $WORKDIR/keyring "$KEYRING"
+        }        
     ;;
     MAC)
-    mount | grep 'JaroTmp' > /dev/null
-    { test $? = 0 } && {
-        # our RAM temp directory is active
-        TMPDIR=/Volumes/JaroTmp/jaromail.$USER
-        TMPRAM=1
-    }
     ;;
 esac
-
-# use the TMP in RAM if possible, for acceleration
-{ test $TMPRAM = 1 } && {
-    act "Using temporary directory in volatile RAM" }
-
-# make sure we have a temp dir
-${=mkdir} "$TMPDIR"
-{ test $? != 0 } && {
-    error "Cannot create temporary directory: $TMPDIR"
-    return 1 }
 
 hostname=$(hostname) # gather the current hostname
 
@@ -274,65 +314,6 @@ GNOMEKEY=0
 pidof gnome-keyring-daemon > /dev/null && {
      act "using gnome-keyring to store secrets"
      GNOMEKEY=1 }
-
-
-cleanexit() {
-    func "Clean exit procedures"
-
-    # security check
-    { test "$TMPDIR" = "" } && {
-    error "Temporary directory not defined"
-    act "skipping cleanup, this might leave private traces."
-    return 1
-    }
-
-    # first delete dirs
-    tmpdirs=`${=find} "$TMPDIR" -maxdepth 1 -type d`
-    for d in ${(f)tmpdirs}; do
-    { test "$d" = "$TMPDIR" } || {
-        func "deleting dir: $d"
-        ${=rm} -r "${d}" }
-    done
-
-    # then locks, with a warning
-    llist=`${=find} "$TMPDIR" -maxdepth 1 -type f -name '*.lock'`
-    for l in ${(f)llist}; do
-    lname=`basename ${(s:.lock:)l}`
-    func "cleaning lock for $lname"
-
-    # skip if in course of unlink - parallel operation, see unlink()
-    pidfile="${TMPDIR}/$lname.pid"
-    if [ -r ${pidfile} ]; then
-        pid=`cat $pidfile`
-        func "forced removal of lock left by pid $pid: $lname"
-        rm -f ${pidfile}
-    else
-        func "forced removal of lock left by unknown pid: $lname"
-    fi
-    rm -f "${TMPDIR}/${lname}.lock"
-
-    # remove the actual file
-    if [ -r "${TMPDIR}/$lname" ]; then
-        func "deleting temp file: ${TMPDIR}/$lname"
-        ${=rm} "${TMPDIR}/$lname"
-    else func "empty lock: file was already removed"; fi
-
-    done
-
-
-#    { test $TMPRAM = 1 } && { rmdir $TMPDIR }
-}
-# make sure tmp is wiped from sensitive data in case of sigINT
-TRAPINT() {
-    error "Caught signal, aborting operations."
-
-    { test $CLEANEXIT = 1 } && {
-        func "Forcing removal of locks"
-        cleanexit & }
-
-    if [ "$DEBUG" = "1" ]; then return 1
-    else exit 1; fi
-}
 
 # binary programs recognition
 check_bin() {
@@ -388,7 +369,7 @@ check_bin() {
     fi
     func "Mutt binary: $mutt"
     # make sure there is always a muttpass file even if empty
-    touch $TMPDIR/muttpass
+    touch $MAILDIR/tmp/muttpass
     return 0
 }
 
@@ -713,7 +694,7 @@ main()
     learn)    CLEANEXIT=0; learn ${PARAM}          ;;
     forget)   CLEANEXIT=0; forget ${PARAM}         ;;
 
-    import)  import_addressbook "${PARAM}" ;;
+    import)  import ${PARAM} ;;
     "export")
             case "$PARAM" in
                 abook)
@@ -728,9 +709,9 @@ main()
 
     abook)   edit_abook ${PARAM}         ;;
 
-    edit|vim)    CLEANEXIT=0; edit_file ${PARAM}    ;;
-    open)    CLEANEXIT=0; open_folder ${PARAM}  ;;
-    preview) CLEANEXIT=0; preview_file ${PARAM} ;;
+    edit|vim)  CLEANEXIT=0; edit_file ${PARAM}    ;;
+    open)      CLEANEXIT=0; open_folder ${PARAM}  ;;
+    preview)   CLEANEXIT=0; preview_file ${PARAM} ;;
 
     backup)  backup ${PARAM}  ;;
     rmdupes) rmdupes ${PARAM} ;;
@@ -801,18 +782,18 @@ main()
         ;;
 
     list|extract)
-            extract ${PARAM}
-            exitcode=$?
-            ;;
+        extract ${PARAM}
+        exitcode=$?
+        ;;
 
     *) # unknown command, pass it to autostart
         func "unknown command, remote check"
         autostart ${PARAM}
         exitcode=$?
         { $exitcode != 0 } && {
-        error "command \"$subcommand\" not recognized"
-        act "try -h for help"
-        CLEANEXIT=0
+            error "command \"$subcommand\" not recognized"
+            act "try -h for help"
+            CLEANEXIT=0
         }
         ;;
     esac
@@ -822,5 +803,4 @@ main()
 
 check_bin
 main $@
-{ test "$CLEANEXIT" = "1" } && { cleanexit & }
 return $exitcode
diff --git a/src/zlibs/email b/src/zlibs/email
--- a/src/zlibs/email
+++ b/src/zlibs/email
@@ -38,104 +38,73 @@ queue() {
     # set it ready for saving in outbux
     queue_body="$base"
 
+    _tmp_create
+    tmpqueue="$JAROTMP"
+
     # pre-processing of the email headers
-    cat | awk '
+    awk '
 /User-Agent:/ { print "User-Agent: Jaro Mail <http://jaromail.dyne.org>"; next }
 { print $0 }
-' > "$TMPDIR/${queue_body}.mail"
+' > "$tmpqueue"
 
     maildirmake "$MAILDIRS/outbox"
-    { test $? = 0 } || {
-    act "updating outbox format to Maildir"
-    # silently migrate the outbox from the old format to the new
-    tmpp=(`find "$MAILDIRS/outbox" -type f`)
-    if [ ${#tmpp} = 0 ]; then
-        # the old format outbox is just empty
-        rmdir "$MAILDIRS/outbox"
-        maildirmake "$MAILDIRS/outbox"
-    else
-        # there are some mails to be sent in the old format outbox
-        # preserve them while migrating to the new format
-        # this code is less interesting, since it handles an old
-        # format in JaroMail
-        tmppp="$TMPDIR/jaro-outbox-migration-$RANDOM"
-        mkdir -p $tmppp
-        mv "$MAILDIRS/outbox/*" $tmppp/
-        rmdir "$MAILDIRS/outbox"
-        maildirmake "$MAILDIRS/outbox"
-        # here we devince two useful arrays:
-        # bodies: the list of mail bodies to send
-        # corresponding to files with same name and extension .msmtp
-        bodies=(`find "$tmppp" -type f -name '*.mail'`)
-        for i in ${bodies}; do
-        cat "$i" | deliver outbox
-        { test $? = 0 } && { rm "$i" }
-        done
-        rmdir $tmppp
-    fi
-    }
     ${=mkdir} "$MAILDIRS/outbox/send"
-
     lock "$MAILDIRS/outbox"
 
     # check if recipients are a Group
     if [[ "${=queue_to}" =~ '@jaromail.group' ]]; then
-
-
-    groupfile="`print ${=queue_to}|cut -d@ -f1`"
-    act "email recipients are in group ${groupfile}"
-
-    { test -r "$MAILDIRS/Groups/$groupfile" } || {
-        maildirmake "$MAILDIRS/postponed"
-        mv "${TMPDIR}/${queue_body}.mail" "$MAILDIRS/postponed/new"
-        unlock "$MAILDIRS/outbox"
-        error "Group not found: $groupfile"
-        return 1 }
-
-    recipients=`cat "$MAILDIRS/Groups/$groupfile" | grep -v '^#'`
-    groupnum=`print ${recipients} | wc -l`
-    groupmode=`head -n1 "$MAILDIRS/Groups/$groupfile" | awk '/^#mode/ { print $2 } { next }'`
-    { test "$groupmode" = "" } && { groupmode="individual" }
-    act "$groupnum recipients in total, sending mode $groupmode"
-
-
-    case $groupmode in
-
-        # individual group mode hides other recipients and send
-        # multiple mail envelopes with each single recipient in To:
-        individual)
-        for i in ${(f)recipients}; do
-            ig=${base}-${RANDOM}
-            cat "${TMPDIR}/${queue_body}.mail" | \
-            awk '/^To:/ { print "'"To: $i"'"; next } { print $0 }' \
-            > "${MAILDIRS}/outbox/new/${ig}.mail"
-        done
-        ;;
-
-        # carboncopy group mode sends a single envelope where all
-        # recipients can see and reply to each other
-        carboncopy|cc)
-        cc=""
-        for i in ${(f)recipients}; do
-            if [ "$cc" = "" ]; then cc="$i"
-            else cc+=", $i"; fi
-        done
-        ig=${base}-${RANDOM}
-        cat "${TMPDIR}/${queue_body}.mail" | \
-            awk '/^To:/ { print "'"To: $cc"'"; print "'"Reply-To: $cc"'"; next }
+        
+        groupfile="`print ${=queue_to}|cut -d@ -f1`"
+        act "email recipients are in group ${groupfile}"
+        
+        [[ -r "$MAILDIRS/Groups/$groupfile" ]] || {
+            maildirmake "$MAILDIRS/postponed"
+            mv "$tmpqueue" "$MAILDIRS/postponed/new"
+            unlock "$MAILDIRS/outbox"
+            error "Group not found: $groupfile"
+            return 1 }
+        
+        recipients=`cat "$MAILDIRS/Groups/$groupfile" | grep -v '^#'`
+        groupnum=`print ${recipients} | wc -l`
+        groupmode=`head -n1 "$MAILDIRS/Groups/$groupfile" | awk '/^#mode/ { print $2 } { next }'`
+        [[ "$groupmode" = "" ]] && { groupmode="individual" }
+        act "$groupnum recipients in total, sending mode $groupmode"
+        
+        case $groupmode in
+            
+            # individual group mode hides other recipients and send
+            # multiple mail envelopes with each single recipient in To:
+            individual)
+                for i in ${(f)recipients}; do
+                    ig=${base}-${RANDOM}
+                    cat "$tmpqueue" | \
+                        awk '/^To:/ { print "'"To: $i"'"; next } { print $0 }' \
+                        > "${MAILDIRS}/outbox/new/${ig}.mail"
+                done
+                ;;
+            
+            # carboncopy group mode sends a single envelope where all
+            # recipients can see and reply to each other
+            carboncopy|cc)
+                cc=""
+                for i in ${(f)recipients}; do
+                    if [ "$cc" = "" ]; then cc="$i"
+                    else cc+=", $i"; fi
+                done
+                ig=${base}-${RANDOM}
+                cat "$tmpqueue" | \
+                    awk '/^To:/ { print "'"To: $cc"'"; print "'"Reply-To: $cc"'"; next }
                 { print $0 }' \
                     > "${MAILDIRS}/outbox/new/${ig}.mail"
-        ;;
-    esac
-
+                ;;
+        esac
+        
     else
-    # recipients are set in the email envelope
-    cat "$TMPDIR/$queue_body.mail" | deliver "outbox"
+        # recipients are set in the email envelope
+        cat "$tmpqueue" | deliver "outbox"
     fi
-
+    
     unlock "$MAILDIRS/outbox"
-    { test -r "${TMPDIR}/${queue_body}.mail" } && {
-    ${=rm} "${TMPDIR}/${queue_body}.mail" }
 
     return 0
 }
@@ -338,7 +307,10 @@ send() {
         # check if this is an anonymous mail
         hdr "$qbody" | grep -i '^from: anon' > /dev/null
         if [[ $? = 0 ]]; then
-            anoncfg="${TMPDIR}/${smtp}.anon.$RANDOM"
+
+            _tmp_create
+            anoncfg="$JAROTMP"
+
             cat <<EOF > "$anoncfg"
 REMAIL		n
 POOLSIZE	0
@@ -388,8 +360,6 @@ BEGIN { head=1 }
                 mv "$qbody.anon" "$qbody"
                 func "mixmaster returns $res"
             done
-
-            ${=rm} $anoncfg
 
         else # normal send with msmtp
 
@@ -485,23 +455,26 @@ peek() {
         error "Error retrieving password for $login on $imap"
         unset password all; return 1
     }
-    tmp="$TMPDIR/$imap.peek.$RANDOM"
-    newlock "$tmp"
+
+    _tmp_create
+    tmp="$JAROTMP"
     cat <<EOF >> "$tmp"
 set imap_pass = "${password}"
 # set imap_peek = yes
 EOF
     unset password
-    print "source '$tmp'" > "$TMPDIR/muttpass"
     # when peeking don't mark unread messages as Old
     # and sort date received with no threading (latest up)
-    cat <<EOF >> "$TMPDIR/muttpass"
+    touch "$MAILDIRS/tmp/muttpass"
+    cat <<EOF >> "$MAILDIRS/tmp/muttpass"
+source '$tmp'
 unset mark_old
 set sort=reverse-date-received
 EOF
+    # fork a process to delete the pass files after use
     (sleep 1;
-        cp /dev/null "$TMPDIR/muttpass"
-        unlink "$tmp" # secure delete in ram
+        cp /dev/null "$MAILDIRS/tmp/muttpass"
+        cp /dev/null "$tmp" # zero the tmp passfile
     ) &
     ${=mutt} -F $MUTTDIR/rc	-f ${iproto}://${ilogin}@${imap}:${imap_port}/${folder}
 
diff --git a/src/zlibs/maildirs b/src/zlibs/maildirs
--- a/src/zlibs/maildirs
+++ b/src/zlibs/maildirs
@@ -92,57 +92,55 @@ rmdupes() {
 
     ## special argument lastlog
     { test "$1" = "lastlog" } && {
-    lastdirs=(`maildirs_lastlog`)
-    act "Pruning duplicates across ${#lastdirs} destination maildirs:"
-    act "${lastdirs}"
-    # recursion here
-    rmdupes ${=lastdirs}
-    notice "Done pruning"
-    # all the prioritization above is so that duplicates are spotted
-    # across different maildirs and deleted from the filtered source
-    return 0
+        lastdirs=(`maildirs_lastlog`)
+        act "Pruning duplicates across ${#lastdirs} destination maildirs:"
+        act "${lastdirs}"
+        # recursion here
+        rmdupes ${=lastdirs}
+        notice "Done pruning"
+        # all the prioritization above is so that duplicates are spotted
+        # across different maildirs and deleted from the filtered source
+        return 0
     }
     ###############
-
+    
     tot=0
     typeset -al msgs
-
-    formail_cache="$TMPDIR/filter.rmdupes.$datestamp.$RANDOM"
-    newlock "$formail_cache"
-
+    
+    _tmp_create
+    formail_cache="$JAROTMP"
+    
     for folder in ${=@}; do
-    { test -r "$folder" } || { folder="$MAILDIRS/$folder" }
-    { test -r "$folder" } || {
-        error "Directory not found: $folder"
-        continue }
-
-    { maildircheck "${folder}" } || {
-        error "Not a maildir folder: $folder"
-        continue }
-
-    c=0
-    notice "Checking for duplicates in $folder"
-    msgs=`${=find} "${folder}" -maxdepth 2 -type f`
-    act "Please wait, this can take a while..."
-
-
-
-    for m in ${(f)msgs}; do
-        func "formail < $m"
-        # 128MB should be enough ehre?
-        formail -D 128000000  "$formail_cache" <"$m" \
-        && rm "$m" && c=$(( $c + 1 ))
+        { test -r "$folder" } || { folder="$MAILDIRS/$folder" }
+        { test -r "$folder" } || {
+            error "Directory not found: $folder"
+            continue }
+        
+        { maildircheck "${folder}" } || {
+            error "Not a maildir folder: $folder"
+            continue }
+        
+        c=0
+        notice "Checking for duplicates in $folder"
+        msgs=`${=find} "${folder}" -maxdepth 2 -type f`
+        act "Please wait, this can take a while..."
+        
+        
+        
+        for m in ${(f)msgs}; do
+            func "formail < $m"
+            # 128MB should be enough ehre?
+            formail -D 128000000  "$formail_cache" <"$m" \
+                && rm "$m" && c=$(( $c + 1 ))
+        done
+        act "$c duplicates found and deleted"
+        tot=$(( $tot + $c ))
     done
-    act "$c duplicates found and deleted"
-    tot=$(( $tot + $c ))
-    done
-
-    unlink "$formail_cache"
-
+    
     if [ "$tot" = "0" ]; then
-    act "No duplicates found at all"
+        act "No duplicates found at all"
     else
-    act "$tot total duplicates found and deleted"
+        act "$tot total duplicates found and deleted"
     fi
 }
 
