password handling using gnome-keyring on GNU systems

diff --git a/src/jaro b/src/jaro
--- a/src/jaro
+++ b/src/jaro
@@ -222,9 +222,10 @@ ask_password() {
 	    func "Looking for password in keyring: $1 @ $2"
 	    security find-internet-password -a $1 -s $2 > /dev/null
 	    if [ $? != 0 ]; then # its a new password
-		password=`pin_entry $1 @ $2`
-		act "New password set for $1 @ $2"
-		security add-internet-password -a $1 -s $2 -w "${password}"
+		new_password
+		{ test $? = 0 } && {
+		    error "Password input aborted."
+		    return 1 }
 	    else
 		act "Using saved password for $1 @ $2"
 		password=`security find-internet-password -a $1 -s $2 -g \
@@ -232,13 +233,20 @@ ask_password() {
 	    fi
 	    return 0
 	    ;;
+	#####################################
 	GNU)
-	    password=`pin_entry $login $host`
-	    if [ "$password" != "" ]; then
-		return 0
-	    else
-		return 1
+	    func "Looking for password in keyring: $1 @ $2"
+	    echo "protocol=${type}\npath=jaromail/${email}\nusername=${login}\nhost=${host}\n\n" | $WORKDIR/bin/jaro-gnome-keyring check
+	    if [ $? != 0 ]; then # its a new password
+		new_password
+		{ test $? = 0 } && {
+		    error "Password input aborted."
+		    return 1 }
+	    else # password found into gnome keyring
+		act "Using saved password for $1 @ $2"
+		password=`echo "protocol=${type}\npath=jaromail/${email}\nusername=${login}\nhost=${host}\n\n" | $WORKDIR/bin/jaro-gnome-keyring get`
 	    fi
+	    return 0
 	    ;;
 	*)
 	    error "Unknown system, can't figure out how to handle passwords"
@@ -246,6 +254,49 @@ ask_password() {
     esac
 }
 
+new_password() {
+    case $OS in
+	MAC)
+	    password=`pin_entry $1 $2`
+	    act "New password set for $1 @ $2"
+	    security add-internet-password -a $1 -s $2 -w "${password}"
+	    # TODO: erase and error codes
+	    ;;
+	GNU)
+	    notice "Setting a new password for $login @ $host"
+	    password=`pin_entry $login $host`
+	    if [ "$password" != "" ]; then
+		cat <<EOF | $WORKDIR/bin/jaro-gnome-keyring store
+protocol=${type}
+path=jaromail/${email}
+username=${login}
+host=${host}
+password=${password}
+EOF
+		{ test $? != 0 } && {
+		    unset password
+		    error "Error saving password in Gnome keyring"
+		    return 1 }
+		return 0
+	    else
+		cat <<EOF | $WORKDIR/bin/jaro-gnome-keyring erase
+protocol=${type}
+path=jaromail/${email}
+username=${login}
+host=${host}
+EOF
+		{ test $? != 0 } && {
+		    error "Error accessing password in Gnome keyring"
+		    return 1 }
+		act "No new password given, old password erased."
+		return 0
+	    fi		
+	    ;;
+	*)
+	    error "Unknown system, can't figure out how to handle passwords"
+	    return 1
+    esac
+}
 switch_identity() {
     if [ "$name" != "" ]; then
 	act "switch to identity: $name <$login>"
@@ -304,8 +355,9 @@ maildirmake() {
 read_account() {
     typeset -al all
 
-    if [ -z $1 ]; then type="*"
-
+    if [ -z $1 ]; then
+	type=`echo $account | cut -d. -f1`
+	account=`echo $account | cut -d. -f2`
     else type=$1 # smtp, imap, pop ... file prefixes"
     fi
 
@@ -313,12 +365,14 @@ read_account() {
     for a in `find $WORKDIR/Accounts -name "$type.$account*"`; do all+=($a); done
     if [ ${#all} = 0 ]; then
 	error "No $type account found: $account"
+	error "Refine your argument using 'type.account'"
+	error "For instance: imap.default or smtp.default"
 	return 1
     elif [ ${#all} != 1 ]; then
 	error "Too many $type accounts named $account"
 	act -n ""
 	for i in ${=all}; do echo -n "`basename ${i}` "; done
-	echo; error "Refine your account keyword"
+	echo; error "Refine your account keyword using -a option"
 	return 1
     fi
 
@@ -557,11 +611,10 @@ fetch() {
 
     notice "Fetching mails for $name"
     ask_password $login $host
-    if [ $? != 0 ]; then
+    { test $? != 0 } && {
 	error "Error retrieving password for $login on $host"
-	unset password all
-	return 1
-    fi
+	unset password all; return 1
+    }
 
     newlock $WORKDIR/tmp/$host.fetch
     cat <<EOF > $WORKDIR/tmp/$host.fetch
@@ -663,6 +716,10 @@ send() {
 
 
     ask_password $login $host
+    { test $? != 0 } && {
+	error "Error retrieving password for $login on $host"
+	unset password all; return 1
+    }
 
     newlock $WORKDIR/tmp/$host.send
     cat <<EOF > $WORKDIR/tmp/$host.send
@@ -733,6 +790,12 @@ peek() {
     sleep 2
     # escape at sign in login
     ilogin=`echo $login | sed 's/@/\\@/'`
+    ask_password $login $host
+    { test $? != 0 } && {
+	error "Error retrieving password for $login on $host"
+	unset password all; return 1
+    }
+
     mutt -F $MUTTDIR/rc -f ${iproto}://${ilogin}@${host}${folder}
     # TODO automatic input of password in mutt
     return $?
@@ -1142,6 +1205,8 @@ Options:
 
 Maintenance commands:
 
+ passwd   reset password for the account in use
+
  update   refresh configurations
  queue    add a mail into outbox
 
@@ -1190,6 +1255,7 @@ main()
     subcommands_opts[merge]=""
     subcommands_opts[filter]=""
 
+    subcommands_opts[passwd]=""
     subcommands_opts[cert]=""
 
     subcommands_opts[source]=""
@@ -1290,6 +1356,9 @@ main()
 	merge)   merge ${PARAM} ;;
 	filter)  filter ${PARAM} ;;
 
+	passwd)  read_account;
+	    { test $? = 0 } && { new_password ${PARAM} }
+	    ;;
 	cert)    cert ${PARAM} ;;
 
 	'source')   CLEANEXIT=0; return 0 ;;
