separated install mutt configuration some fixes

diff --git a/src/postino b/src/postino
--- a/src/postino
+++ b/src/postino
@@ -20,21 +20,31 @@
 # this source code; if not, write to:
 # Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 
-VERSION=0.5
-DATE=Sept/2011
+VERSION=0.6
+DATE=March/2011
 POSTINOEXEC=$0
 typeset -a OLDARGS
 for arg in ${argv}; do OLDARGS+=($arg); done
 
-#declare global variables
+##########################
+# declare global variables
+
 QUIET=0
-DEBUG=0
+DEBUG=1
+
+# default config dir
+if [ -z $POSTINO_DIR ]; then
+    WORKDIR=$HOME/.postino
+else
+    WORKDIR=$POSTINO_DIR
+fi
+
+##########################
+
+
 PARAM=()
 typeset -A global_opts
 typeset -A opts
-
-# make sure we have a temp dir
-mkdir -p $WORKDIR/tmp
 
 autoload colors; colors
 
@@ -53,20 +63,20 @@ act()    {
     fi
 }
 
-
-# parse configuration
-if [ -r $HOME/.postinorc ]; then source $HOME/.postinorc
-else WORKDIR=$HOME/.postino; fi # default
-
-
-if [ -r $WORKDIR/main.conf ]; then
-    source $WORKDIR/main.conf
-else # first run (main conf not found)
-    notice "This is the first time you run postino on this machine,"
-    act "we will now call a wizard that will assist you through the configuration"
-    error "WIZARD TODO"
-    return 0
+# make sure the directory is private
+chmod 700 $WORKDIR
+if [ $? != 0 ]; then
+    error "Postino directory $WORKDIR is not private, set permissions to 700"
+    error "Refusing to proceed."
+    exit 1
 fi
+
+# make sure we have a temp and cache dir
+mkdir -p $WORKDIR/tmp $WORKDIR/cache
+chmod 700 $WORKDIR/tmp $WORKDIR/cache
+
+
+
 
 # we use pinentry
 # comes from gpg project and is secure
@@ -111,6 +121,24 @@ option_is_set() {
 option_value() {
     #First argument, the option (something like "-s")
     <<< ${opts[$1]}
+}
+maildirmake() {
+
+    if [ -z $1 ]; then
+	error "internal error: missing argument for maildirmake"
+	return
+    fi
+
+    if [ -r $1 ]; then
+	func "maildir exists: $1"
+	return
+    fi
+
+    mkdir -p ${1}/cur
+    mkdir -p ${1}/new
+    mkdir -p ${1}/tmp
+    
+    chmod -R 700 $1
 }
 
 queue() {
@@ -171,12 +199,12 @@ send() {
 peek() {
     # this function will open the MTA to the imap server without fetching mails locally
     local -aU imap_set #behave like a set; that is, an array with unique elements
-    imap_set=`awk '!/^#/ { print $1 ";" $2 ";" $3 }' $WORKDIR/receive.conf`
+    imap_set="${IMAP_LOGIN};${IMAP_ADDRESS};${IMAP_PORT}"
     for i in ${(f)imap_set}; do
+	ilogin="${i[(ws:;:)1]}"
 	ihost="${i[(ws:;:)2]}"
-	ilogin="${i[(ws:;:)3]}"
-	iname="${i[(ws:;:)1]}"
-	func "IMAP: $iname $ilogin $ihost:$iport"
+	iport="${i[(ws:;:)3]}"
+	func "IMAP: $ilogin $ihost:$iport"
 	# if there is a selection, check if its the one
 	if [ $1 ] && [ "$1" == "$iname" ]; then break;
 	elif ! [ $1 ]; then break; fi # no selection: take first as default
@@ -198,44 +226,65 @@ sync() {
     func "WORKDIR: $WORKDIR"
     func "MAILDIRS: $MAILDIRS"
 
+    # make sure maildirs where to put mails exist
+    mkdir -p $MAILDIRS
+    chmod 700 $MAILDIRS
+    maildirmake $MAILDIRS/known
+    maildirmake $MAILDIRS/sent
+    maildirmake $MAILDIRS/priv
+    maildirmake $MAILDIRS/postponed
+    maildirmake $MAILDIRS/unsorted
+    
     ######
     # MUTT
-    mkdir -p $WORKDIR/mutt
-    rm -f $WORKDIR/mutt/rc
-    cat<<EOF > $WORKDIR/mutt/rc
+    if ! [ -z $MUTTDIR ]; then
+	mkdir -p $MUTTDIR
+	rm -f $MUTTDIR/rc
+	cat<<EOF > $MUTTDIR/rc
 # mutt config generated by postino
 unset use_domain
-set hostname = "dyne.org"
-set realname = "jaromil"
-set folder = ~/$MAILDIRS
-set spoolfile = ~/$MAILDIRS/known/
-set record = ~/$MAILDIRS/sent/
-set postponed=~/$MAILDIRS/postponed/
+set hostname = $DOMAIN
+set realname = $NAME
+set folder = $MAILDIRS
+set spoolfile = $MAILDIRS/known/
+set record = $MAILDIRS/sent/
+set postponed= $MAILDIRS/postponed/
 set tmpdir = $WORKDIR/tmp
 set query_command = "postino query '%s'"
 set sendmail = "postino queue"
-set header_cache=~/$WORKDIR/mutt/cache
+set header_cache= $MUTTDIR/cache
 set maildir_header_cache_verify=no
+set editor = "$EDITOR"
+set mailcap_path = "$WORKDIR/mailcap"
+
 # mailboxes in order of priority
-source $WORKDIR/mutt/mboxes
-## end of postino muttrc
+source $MUTTDIR/mboxes
 EOF
 
-    # just the header, will be completed later in procmail loop
-    rm -f $WORKDIR/mutt/mboxes
-    echo -n "mailboxes +priv" > $WORKDIR/mutt/mboxes
+	if [ -r $MUTTDIR/general ]; then
+	    echo "# user tweaked configuration" >> $MUTTDIR/rc
+	    echo "source ${MUTTDIR}/general" >> $MUTTDIR/rc
+	fi
+	echo "## end of generated muttrc" >> $MUTTDIR/rc
+	echo "##########################" >> $MUTTDIR/rc
+	echo >> $MUTTDIR/rc
 
+        # just the header, will be completed later in procmail loop
+	rm -f $WORKDIR/mutt/mboxes
+	echo -n "mailboxes +priv" > $WORKDIR/mutt/mboxes
+    fi
+    
     ##########
     # PROCMAIL
-    mkdir -p $WORKDIR/procmail
-    rm -f $WORKDIR/procmail/rc
-    touch $WORKDIR/procmail/rc
-    cat<<EOF >> $WORKDIR/procmail/rc
+    mkdir -p $PROCMAILDIR
+    rm -f $PROCMAILDIR/rc
+    touch $PROCMAILDIR/rc
+    cat<<EOF >> $PROCMAILDIR/rc
 # procmail configuration file generated by postino
 MAILDIR=$MAILDIRS
 DEFAULT=unsorted/
 VERBOSE=off
-LOGFILE=$WORKDIR/procmail/log
+LOGFILE=$PROCMAILDIR/log
 SHELL       = /bin/sh       # VERY IMPORTANT
 UMASK       = 007           # James Bond :-)
 LINEBUF     = 8192          # avoid procmail choke
@@ -260,25 +309,26 @@ EOF
 	case $header in
 	    to)
 		print "ADDR=${address}\tDEST=${destination}\tINCLUDERC=$PMSRC/pf-chkto.rc" \
-		    >> $WORKDIR/procmail/rc
+		    >> $PROCMAILDIR/rc
 		;;
 	    from)
 		print "ADDR=${address}\tDEST=${destination}\tINCLUDERC=$PMSRC/pf-check.rc" \
-		    >> $WORKDIR/procmail/rc
+		    >> $PROCMAILDIR/rc
 		;;
 	    *)
 		error "unsupported in filters.conf: $header (skipped)"
 		;;
 	esac
 	# MUTT (generate mailboxes priority this parser)
-	echo  " \\" >> $WORKDIR/mutt/mboxes
-	echo -n " +${destination} " >> $WORKDIR/mutt/mboxes
+	echo  " \\" >> $MUTTDIR/mboxes
+	echo -n " +${destination} " >> $MUTTDIR/mboxes
     done
 
-    echo " \\" >> $WORKDIR/mutt/mboxes
-    echo " +unsorted" >> $WORKDIR/mutt/mboxes
-    uniq $WORKDIR/mutt/mboxes > $WORKDIR/tmp/mboxes
-    mv $WORKDIR/tmp/mboxes $WORKDIR/mutt/mboxes
+    echo " \\" >> $MUTTDIR/mboxes
+    echo " +unsorted" >> $MUTTDIR/mboxes
+    uniq $MUTTDIR/mboxes > $WORKDIR/tmp/mboxes
+    mv $WORKDIR/tmp/mboxes $MUTTDIR/mboxes
+    rm -f $WORKDIR/tmp/mboxes
 
     cat <<EOF >> $WORKDIR/procmail/rc
 }
@@ -293,18 +343,6 @@ EOF
 :0 w:
 * ? formail -x"From:" | head -n1 | tr 'A-Z' 'a-z' | sed 's/.*\W\([0-9a-z_.-]\+@[0-9a-z_.-]\+\).*/\1/' | xargs lbdbq
 known/
-
-# if the destination is known, put it in private folder
-:0
-* ? test $PMSRC/pf-chkto.rc
-{
-  ADDR="(jaromil@dyne.org)"	DEST=priv/	INCLUDERC=$PMSRC/pf-chkto.rc
-  ADDR="(jaromil@nimk.nl)"	DEST=priv/	INCLUDERC=$PMSRC/pf-chkto.rc
-  ADDR="(jaromil@kyuzz.org)"	DEST=priv/	INCLUDERC=$PMSRC/pf-chkto.rc
-  ADDR="(jaromil@enemy.org)"	DEST=priv/	INCLUDERC=$PMSRC/pf-chkto.rc
-  ADDR="(j@rastasoft.org)"	DEST=priv/	INCLUDERC=$PMSRC/pf-chkto.rc
-  ADDR="(denis@roio.net)"	DEST=priv/	INCLUDERC=$PMSRC/pf-chkto.rc
-}
 
 # if got here, go to unsorted
 
@@ -342,6 +380,7 @@ main()
     subcommands_opts[sync]=""
     subcommands_opts[conf]=""
     subcommands_opts[list]=""
+    subcommands_opts[source]=""
 #    subcommands_opts[mount]=${subcommands_opts[open]}
 #    subcommands_opts[create]="s: -size=s -ignore-swap k: -key=k"
     ### Detect subcommand
@@ -410,6 +449,7 @@ main()
 	peek) peek ;;
 	sync) sync ;;
 	conf) ;;
+	'source')   return 0 ;;
 	__default) ;;
 	*) error "command \"$subcommand\" not recognized"
 	    act "try -h for help"
